/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import entidades.Tablero;
import entidades.Tarea;
import entidades.Usuario;
import interfaces.INegocios;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jjavi
 */
public class PantallaSeleccion extends javax.swing.JFrame {

    private INegocios negocios;
    private Usuario usuario;

    public PantallaSeleccion(INegocios negocios, Usuario usuario) {
        initComponents();

        this.negocios = negocios;
        this.usuario = usuario;

        llenarTabla();
    }

    private void llenarTabla() {
        List<Tablero> listaTableros = this.negocios.consultarTableros();
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tblTableros.getModel();
        modeloTabla.setRowCount(0);
        listaTableros.forEach(tablero -> {
            Object[] fila = new Object[1];
            fila[0] = tablero;
            modeloTabla.addRow(fila);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTableros = new javax.swing.JTable();
        btnCrearTablero = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selecciona tablero");

        tblTableros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tablero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTableros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablerosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTableros);

        btnCrearTablero.setText("Crear Tablero");
        btnCrearTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTableroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCrearTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrearTablero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTableroActionPerformed
        NuevoTableroDialog tableroDlg = new NuevoTableroDialog(this, true, negocios);

        llenarTabla();
    }//GEN-LAST:event_btnCrearTableroActionPerformed

    private void tblTablerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablerosMouseClicked
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tblTableros.getModel();
        int row = tblTableros.getSelectedRow();
        int colum = tblTableros.getSelectedColumn();
        Tablero tablero = (Tablero) modeloTabla.getValueAt(row, colum);
        Board board = new Board(negocios, usuario, tablero);
        board.setVisible(true);
    }//GEN-LAST:event_tblTablerosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCrearTablero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTableros;
    // End of variables declaration//GEN-END:variables
}
